### ISSUE TITLE
check dependencies recursively

### ISSUE THREAD

**Issue by liamuk** [tminglei/browserify-bower#3]
if you require a bower component with dependencies that aren't dependencies of your project as a whole, browserify-bower won't discover and include them. 

You may want to consider using bower's programmatic api with bower.command.list to get the dependency tree.

**Comment by tminglei** [comment]
Thank you for pointing it out, I'll implement is ASAP.
_(p.s. I can't start it until next week, since I'm very busy these days.)_

**Comment by tminglei** [comment]
Hi @liamuk, did you execute `bower install` to fetch its all dependencies before executing browserify tasks?

**Comment by liamuk** [comment]
Yep.

**Comment by tminglei** [comment]
Hi @liamuk, just submitted fixing change, pls help check. Thanks!

_BTW, `bower.command.list` is an async method, I want a sync solution, so I enhance the util method to analysis the deps. :-)_
