### ISSUE TITLE
Bump to v0.4.5 breaks resolution of packages lacking a `bower.json` file

### ISSUE THREAD

**Issue by mhamann** [tminglei/browserify-bower#5]
It seems that the latest updates to v0.4.5 have caused a side-effect of no longer being able to resolve bower packages that lack a true `bower.json` file. I'm personally experiencing this issue with Modernizr, which seems to have a `.bower.json` but no `bower.json` (without the `.`).

It would be helpful if browserify-bower didn't necessarily care about the `bower.json`, though I understand why that's useful. Perhaps it could be optional?

**Comment by tminglei** [comment]
Ok, I'll enhance it.

_BTW, `.bower.json` will always have same structure with `bower.json`, right?_

**Comment by tminglei** [comment]
Hi @mhamann, I released new version, pls help check it.
