### ISSUE TITLE
mainfiles does not support multiple files

### ISSUE THREAD

**Issue by jedierikb** [tminglei/browserify-bower#9]
According to bower spec, mainfiles can include multiple files
https://github.com/bower/spec/blob/master/json.md#main
http://stackoverflow.com/questions/20391742/what-is-the-main-file-property-when-doing-bower-init

However, with your utility we cannot provide a list of mainfiles for a library.  This is problematic when libraries needed require developers to pick and choose a few different files.

**Comment by jedierikb** [comment]
moreover, it does not look like libraries' bower.json `main:['this.js', 'that.js']` are being honored?

**Comment by tminglei** [comment]
ok, I'll try to fix it asap.
_Thanks! :-)_

**Comment by tminglei** [comment]
@jedierikb pls refer to #7, and tell whether it resolved your problem?

**Comment by jedierikb** [comment]
When I try to load in a bower.json file with an array for **main**, it only loads in the first file.
Regarding the code you linked to, if I test it like so:


`['file_one.js', 'file_two.js'].filter(function(file) { return /\.js$/.test(file); })[0]`


the function only returns file_one.js.  I expected it to concatenate the files?

For example, I would like to be able to get all of the .js files from this project's main: 
https://github.com/amsul/pickadate.js/blob/master/bower.json
or, using your tool, pick and choose which .js files I would like to include.

Apologies if I am missing something or doing something wrong and this is already supported or should be done differently.

**Comment by tminglei** [comment]
Well, it only support one main file now, that I thought it should be.
Seems I was wrong. I'll correct it ASAP.

**Comment by tminglei** [comment]
Well, it seems leading to some more related problem when I tried to support multiple main files. I need more time to resolve it.

**Comment by tminglei** [comment]
@jedierikb well, I'll give it up.
_Bower spec requires `Only one file per filetype`, so it's difficult to get a consistent behavior for multiple files per filetype._

To reference another file instead of the first one in the **main**, you can turn to specify it like `comp_name/sub_dir/sub_name` in your conf, which I called `submodule` and was already supported.

**Comment by jedierikb** [comment]
How do I pass in & specify the conf / submodule?  Could you provide an example of how to do this?  Sorry, I cannot figure it out.  Thanks.

**Comment by tminglei** [comment]
In fact, you can find it in the README:
```javascript
b.plugin('browserify-bower', {
    require: ['*', 'base62/lib/base62', 'base62/xxx:xxx'],
    external: {
        exclude: ['comp1', 'comp2']
    },
    alias: ['base62/lib/base62:base62'], // or alias: { 'base62/lib/base62':'base62', ... }
    mainfiles: { // specify the main file for packages without a bower.json
        'base62': 'main.js'
    }
});
```
_here, `base62` is an alias for submodule `base62/lib/base62`, and we specified a manifile `main.js` for it._

**Comment by jedierikb** [comment]
works.  makes sense.  much thanks.

**Comment by tminglei** [comment]
_You're welcome. ;-)_
